name: Release

on: push

jobs:
  Build-Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: abatilo/actions-poetry@v2
    - name: Package xls converter
      run: |
        cd xls-converter/ &&\
        poetry build -f wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xls-converter
        path: xls-converter/dist
  Release:
    if: contains(github.ref, 'tags/v')
    needs:
    - Build-Python
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v2
  Publish-Python:
    if: contains(github.ref, 'tags/v')
    needs: Release
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: xls-converter
        path: .
    - name: Archive
      run: zip -r xls-converter.zip .
    - name: Upload archive
      uses: softprops/action-gh-release@v2
      with:
          files: xls-converter.zip
